[phases.setup]
nixPkgs = ['nodejs-18_x', 'postgresql']

[phases.install]
cmds = [
  'npm install',
  'cd backend && npm ci --only=production'
]

[phases.build]
cmds = [
  'echo "Build completed - no database operations during build"',
  'chmod +x simple-start.js'
]

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
PORT = '5001'
